esphome:
  name: funkytest

# Example configuration entry
switch:
  - platform: gpio
    pin: D4
    name: "LED"


binary_sensor:
  - platform: gpio
    pin: D0
    name: "PIR Sensor"
    device_class: motion

esp8266:
  board: nodemcu

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "DangarSlow"
  password: "nolfonzo"
      # Optional manual IP
      #  manual_ip:
      #    static_ip: 192.168.20.51
      #    gateway: 192.168.20.1
      #    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "D-Link DVA-2800"
    password: "Landrover"

captive_portal:
    
