name: SensESP Automatic Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        example:
          - examples/minimal_app.cpp
          - examples/analog_input.cpp
          - examples/hysteresis.cpp
          - examples/lambda_transform.cpp
          - examples/minimal_app.cpp
          - examples/relay_control.cpp
          - examples/rpm_counter.cpp
          - examples/async_repeat_sensor.cpp
          - examples/repeat_sensor_analog_input.cpp
          - examples/freertos_tasks.cpp
          - examples/raw_json.cpp
        target_device:
          - esp32dev
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: Run PlatformIO
        run: ci/run-ci.sh
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
          CI_TARGET_DEVICE: ${{ matrix.target_device }}
